import { z } from 'zod/mini'

export const Enum = {
	Profession: z.enum([
		'KOREAN_MEDICINE_DOCTOR',
		'DENTIST',
		'MEDICAL_DOCTOR',
		'ACCOUNTANT',
		'LAWYER',
		'TAX_ACCOUNTANT',
		'LEGAL_AFFAIRS_SPECIALIST',
		'ADMINISTRATIVE_SPECIALIST',
		'PROPERTY_APPRAISER',
		'IT_DEVELOPER',
		'IT_ENGINEER',
		'BIOTECHNOLOGY_PHD',
		'MEDICAL_RESEARCHER',
		'ACTUARY',
		'CIVIL_SERVANT',
		'PHARMACIST',
		'PATENT_ATTORNEY',
		'MECHANICAL_ENGINEERING_PHD',
		'INDUSTRIAL_ENGINEERING_PHD',
	]).def.entries,
}

export const ZodEnum = {
	Profession: z.enum([
		'KOREAN_MEDICINE_DOCTOR',
		'DENTIST',
		'MEDICAL_DOCTOR',
		'ACCOUNTANT',
		'LAWYER',
		'TAX_ACCOUNTANT',
		'LEGAL_AFFAIRS_SPECIALIST',
		'ADMINISTRATIVE_SPECIALIST',
		'PROPERTY_APPRAISER',
		'IT_DEVELOPER',
		'IT_ENGINEER',
		'BIOTECHNOLOGY_PHD',
		'MEDICAL_RESEARCHER',
		'ACTUARY',
		'CIVIL_SERVANT',
		'PHARMACIST',
		'PATENT_ATTORNEY',
		'MECHANICAL_ENGINEERING_PHD',
		'INDUSTRIAL_ENGINEERING_PHD',
	]),
}
